"""Умолчания платформы, которые EDT пишет в форме явно.

Снято с корпуса скриптом `tools/edt_form_check.py --умолчания`: для каждого
вида элемента — свойства, которые EDT пишет, когда выгрузка их не задаёт,
с одним значением не меньше чем в 99 % случаев. Ключ — `класс|вид`
(`FormField|InputField`), у спутника — `свойство|вид` (`extendedTooltip|Label`),
у формы — `Form|`; путь свойства вида — `extInfo/имя`.
"""

DEFAULTS = {
    'Addition|': {
        'enabled': 'true',
        'extInfo/autoMaxWidth': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'Addition|SearchControlAddition': {
        'enabled': 'true',
        'extInfo/autoMaxWidth': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'Button|': {
        'autoMaxHeight': 'true',
        'autoMaxWidth': 'true',
        'buttonImportance': 'Normal',
        'enabled': 'true',
        'placementArea': 'UserCmds',
        'representation': 'Auto',
        'representationInContextMenu': 'Auto',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'Button|CommandBarHyperlink': {
        'autoMaxHeight': 'true',
        'autoMaxWidth': 'true',
        'buttonImportance': 'Normal',
        'enabled': 'true',
        'placementArea': 'UserCmds',
        'representation': 'Auto',
        'representationInContextMenu': 'Auto',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'Button|Hyperlink': {
        'autoMaxHeight': 'true',
        'autoMaxWidth': 'true',
        'buttonImportance': 'Normal',
        'enabled': 'true',
        'placementArea': 'UserCmds',
        'representation': 'Auto',
        'representationInContextMenu': 'Auto',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'Button|UsualButton': {
        'autoMaxHeight': 'true',
        'autoMaxWidth': 'true',
        'buttonImportance': 'Normal',
        'enabled': 'true',
        'placementArea': 'UserCmds',
        'representation': 'Auto',
        'representationInContextMenu': 'Auto',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'Decoration|': {
        'autoMaxHeight': 'true',
        'autoMaxWidth': 'true',
        'enabled': 'true',
        'extInfo/fileDragMode': 'AsFileRef',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'Decoration|Label': {
        'autoMaxHeight': 'true',
        'autoMaxWidth': 'true',
        'enabled': 'true',
        'extInfo/horizontalAlign': 'Left',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|CalendarField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'extInfo/border': '@core:BorderDef|style=Single;width=1',
        'extInfo/calendarNavigation': 'true',
        'extInfo/horizontalStretch': 'true',
        'extInfo/verticalStretch': 'true',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|ChartField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/horizontalStretch': 'true',
        'extInfo/verticalStretch': 'true',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|CheckBoxField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|FormattedDocumentField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'extInfo/height': '10',
        'extInfo/horizontalStretch': 'true',
        'extInfo/verticalStretch': 'true',
        'extInfo/width': '50',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|GraphicalSchemaField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'extInfo/edit': 'true',
        'extInfo/height': '10',
        'extInfo/horizontalStretch': 'true',
        'extInfo/verticalStretch': 'true',
        'extInfo/width': '50',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|HTMLDocumentField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'extInfo/height': '10',
        'extInfo/horizontalStretch': 'true',
        'extInfo/verticalStretch': 'true',
        'extInfo/width': '50',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|InputField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'extInfo/chooseType': 'true',
        'extInfo/textEdit': 'true',
        'extInfo/textSize': 'Normal',
        'extInfo/typeDomainEnabled': 'true',
        'extInfo/wrap': 'true',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|LabelField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|PictureField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'extInfo/border': '@core:BorderDef|style=Single;width=1',
        'extInfo/fileDragMode': 'AsFileRef',
        'extInfo/horizontalStretch': 'true',
        'extInfo/verticalStretch': 'true',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|ProgressBarField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'extInfo/height': '1',
        'extInfo/horizontalStretch': 'true',
        'extInfo/maxValue': '100',
        'extInfo/width': '32',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|RadioButtonField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/orientation': 'Vertical',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|SpreadsheetDocumentField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'extInfo/drawingSelectionShowMode': 'Auto',
        'extInfo/enableDrag': 'true',
        'extInfo/enableStartDrag': 'true',
        'extInfo/height': '10',
        'extInfo/horizontalScrollBar': 'ScrollAuto',
        'extInfo/horizontalStretch': 'true',
        'extInfo/pointerType': 'Special',
        'extInfo/selectionShowMode': 'Always',
        'extInfo/showGroups': 'true',
        'extInfo/verticalScrollBar': 'ScrollAuto',
        'extInfo/verticalStretch': 'true',
        'extInfo/width': '50',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormField|TextDocumentField': {
        'editMode': 'Enter',
        'enabled': 'true',
        'extInfo/autoMaxHeight': 'true',
        'extInfo/autoMaxWidth': 'true',
        'extInfo/height': '10',
        'extInfo/horizontalStretch': 'true',
        'extInfo/verticalStretch': 'true',
        'extInfo/width': '50',
        'headerHorizontalAlign': 'Left',
        'showInFooter': 'true',
        'showInHeader': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormGroup|': {
        'enabled': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormGroup|ColumnGroup': {
        'enabled': 'true',
        'extInfo/group': 'Vertical',
        'extInfo/showInCard': 'true',
        'extInfo/showTitle': 'auto',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormGroup|CommandBar': {
        'enabled': 'true',
        'extInfo/horizontalAlign': 'Left',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormGroup|Page': {
        'enabled': 'true',
        'extInfo/group': 'Auto',
        'extInfo/showTitle': 'auto',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormGroup|Pages': {
        'enabled': 'true',
        'extInfo/currentRowUse': 'Auto',
        'extInfo/pagesRepresentation': 'Auto',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormGroup|Popup': {
        'enabled': 'true',
        'extInfo/importance': 'Normal',
        'extInfo/representation': 'Auto',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'FormGroup|UsualGroup': {
        'enabled': 'true',
        'extInfo/behavior': 'Auto',
        'extInfo/currentRowUse': 'Auto',
        'extInfo/group': 'Auto',
        'extInfo/representation': 'Auto',
        'extInfo/showLeftMargin': 'true',
        'extInfo/showTitle': 'auto',
        'extInfo/throughAlign': 'Auto',
        'extInfo/united': 'true',
        'userVisible': '@|common=true',
        'visible': 'true',
    },
    'Form|': {
        'allowFormCustomize': 'true',
        'autoFillCheck': 'true',
        'autoTitle': 'true',
        'autoUrl': 'true',
        'enabled': 'true',
        'group': 'Auto',
        'saveWindowSettings': 'true',
        'showCloseButton': 'true',
        'showTitle': 'auto',
    },
    'Table|': {
        'autoMaxCardHeight': 'true',
        'autoMaxHeight': 'true',
        'autoMaxRowsCount': 'true',
        'autoMaxWidth': 'true',
        'changeRowOrder': 'true',
        'changeRowSet': 'true',
        'enabled': 'true',
        'fileDragMode': 'AsFileRef',
        'footerHeight': '1',
        'header': 'true',
        'headerHeight': '1',
        'horizontalLines': 'true',
        'horizontalScrollBar': 'AutoUse',
        'horizontalStretch': 'true',
        'initialListView': 'Auto',
        'representation': 'HierarchicalList',
        'rowSelectionMode': 'Auto',
        'searchOnInput': 'Auto',
        'selectionMode': 'MultiRow',
        'titleLocation': 'None',
        'userVisible': '@|common=true',
        'verticalLines': 'true',
        'verticalScrollBar': 'AutoUse',
        'verticalStretch': 'true',
        'visible': 'true',
    },
    'attributes|': {
        'edit': '@|common=true',
        'view': '@|common=true',
    },
    'attributes|ChartExtInfo': {
        'edit': '@|common=true',
        'view': '@|common=true',
    },
    'attributes|DynamicListExtInfo': {
        'edit': '@|common=true',
        'extInfo/autoFillAvailableFields': 'true',
        'extInfo/autoSaveUserSettings': 'true',
        'extInfo/getInvisibleFieldPresentations': 'true',
        'view': '@|common=true',
    },
    'attributes|GraphicalSchemeExtInfo': {
        'edit': '@|common=true',
        'view': '@|common=true',
    },
    'attributes|SpreadsheetDocumentExtInfo': {
        'edit': '@|common=true',
        'view': '@|common=true',
    },
    'attributes|ValueListExtInfo': {
        'edit': '@|common=true',
        'view': '@|common=true',
    },
    'autoCommandBar|': {
        'autoFill': 'true',
        'horizontalAlign': 'Left',
    },
    'columns|': {
        'edit': '@|common=true',
        'view': '@|common=true',
    },
    'contextMenu|': {
        'autoFill': 'true',
    },
    'extendedTooltip|Label': {
        'autoMaxHeight': 'true',
        'autoMaxWidth': 'true',
        'extInfo/horizontalAlign': 'Left',
    },
    'formCommands|': {
        'currentRowUse': 'Auto',
        'selectedRowsUse': 'Auto',
        'use': '@|common=true',
    },
    'searchControlAddition|SearchControlAddition': {
        'extInfo/autoMaxWidth': 'true',
    },
    'searchStringAddition|': {
        'extInfo/autoMaxWidth': 'true',
    },
    'viewStatusAddition|ViewStatusAddition': {
        'extInfo/autoMaxWidth': 'true',
    },
}
